yolov8_mod_node:
  ros__parameters:
    model_path: "/home/fantasywilly/weight/Car_Model.pt"
    device: "cuda:0"
    imgsz: 640
    conf_thresh: 0.5
    camera_source: "rtsp://user:user@192.168.144.108:554/cam/realmonitor?channel=1&subtype=0"
    rtsp_server_url: "rtsp://192.168.0.230:8554/live/stream"
    frame_rate: 30
